import {describe, expect, it} from "vitest";
import {normalizeSwerrConfig, validateSwerrConfig} from "../bin/config-schema.js";

describe("Swerr configuration schema", () => {
	it("normalizes canonical fields and defaults", () => {
		const factory = async () => {};
		const config = normalizeSwerrConfig({
			schemaVersion: 1,
			project: {
				name: "Example",
			},
			scan: {
				directories: ["./src", "./packages/shared/src"],
				includeExtensions: ["TS", ".JS"],
			},
			sourceOutput: {
				enabled: false,
			},
			converters: [{factory}],
		});

		expect(config.project).toEqual({
			name: "Example",
			version: "1.0.0",
			description: "Generated by Swerr",
		});
		expect(config.scan.directories).toEqual(["./src", "./packages/shared/src"]);
		expect(config.scan.includeExtensions).toEqual([".ts", ".js"]);
		expect(config.scan.requireErrorTag).toBe(false);
		expect(config.sourceOutput.fileName).toBe("swerr-source.json");
		expect(config.converters).toHaveLength(1);
	});

	it("keeps the current legacy schema working", () => {
		const config = normalizeSwerrConfig({
			sourceFile: {
				inputDirs: ["./src/errors", "./packages/shared/errors"],
				meta: {projectName: "Legacy"},
				export: {saveToFile: true, outputDir: "./docs"},
				options: {
					ignoreDirs: ["fixtures"],
					whitelistExtensions: ["js"],
					requireErrorTag: true,
				},
			},
			converter: [],
		});

		expect(config.project.name).toBe("Legacy");
		expect(config.scan.directories).toEqual(["./src/errors", "./packages/shared/errors"]);
		expect(config.scan.ignoredDirectories).toEqual(["fixtures"]);
		expect(config.scan.includeExtensions).toEqual([".js"]);
		expect(config.scan.requireErrorTag).toBe(true);
		expect(config.sourceOutput).toMatchObject({
			enabled: true,
			directory: "./docs",
		});
	});

	it("rejects configurations without source directories", () => {
		const config = normalizeSwerrConfig({
			scan: {
				directories: [],
			},
		});

		expect(() => validateSwerrConfig(config)).toThrow(
			'Configuration field "scan.directories" must contain at least one directory.',
		);
	});

	it("rejects unsupported schema versions", () => {
		expect(() => normalizeSwerrConfig({schemaVersion: 2, scan: {directories: ["./src"]}}))
			.toThrow('Unsupported configuration schemaVersion "2". Expected 1.');
	});
});
